# General
 pretrained_weights: wanglab/medsam-vit-base
 nameRun: Boxes-Medsam
 seed: 1234
 saveImg_val: True

  
 root_dir: ./output/${nameRun}
 filename: model_checkpoints.pt
 train_output_path: ${root_dir}/train_epoch.txt
 val_output_path: ${root_dir}/val_epoch.txt
 dataset: IRCAD
 json_name: traindebug.json
 batch_size: 2
 max_epochs: 3
 Valbatch_size: 1

 lr: 1e-5
 data_dir: ./data/${dataset}
 json_list: ${data_dir}/${json_name}
 
 prompt: Boxes # PosNegPoints Boxes Box HybridA (Boxes,PosPoints) HybridB (Boxes,PosNegPoints) HybridC (Box,PosPoints) HybridD (Box,PosNegPoints) 
 area_Thr: 800000000 #threshold establish the number of poitns to take
 
 
 wandb_act: False
 entity: xamus86
 project_name: LocalTrials
 dir_wandb: ${root_dir} 
 
 # testing setup
 RunTest: True
 Testjson_name: Twopatients.json
 Testjson_list: ${data_dir}/Test_json/${Testjson_name}
 outTest_dir: ${root_dir}/Test_results/${Testjson_name}
 GTLabels_dir: ${data_dir}/database_labels_nii/Original
 zeroshot: False
